### PR TITLE
[libdvdcss] - allow compilation of libdvdcss for ios

### PR DESCRIPTION
**Pull request by Memphiz**
As the title says - needed for 
https://github.com/xbmc/xbmc/pull/14411

### CODE REVIEW

**Comment by Memphiz** [comment]
@Voyager1 not sure who is allowed to
Merge in this repo - picking you as you have done commits in here :)

It needs a tag aswell so i can reference it in the mentioned PR in kodi then ...

**Comment by Memphiz** [comment]
Or maybe @afedchin - who owns this repo - or are platform maintainers supposed to merge at will?

**Comment by Voyager1** [comment]
thanks @MartijnKaijser and @Memphiz

**Pull request merged**
